export const departNames = [
  "Applied Physics",
  "Agricutural and Agribusiness Management",
  "Applied Chemistry and Chemical Technology",
  "Applied Physics",
  "Arabic",
  "Bangali",
  "Biochemistry",
  "Biotechnology",
  "Botany",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Commerce",
  "Computer Science",
  "Criminology",
  "Economics",
  "Education",
  "English",
  "Food Science and Technology",
  "General History",
  "Genetics",
  "Geography",
  "Geology",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
  "English",
];
