export const departNames = [
  "Applied Physics",
  "Agricutural & Agribusiness Management",
  "Applied Chemistry & Chemical Technology",
  "Applied Physics",
  "Arabic",
  "Bangali",
  "Biochemistry",
  "Biotechnology",
  "Botany",
  "Business Administration",
  "Chemical Engineering",
  "Chemistry",
  "Commerce",
  "Computer Science",
  "Criminology",
  "Economics",
  "Education",
  "English",
  "Food Science & Technology",
  "General History",
  "Genetics",
  "Geography",
  "Geology",
  "Health & Physical Education",
  "International Relations",
  "Islamic History",
  "Islamic Learning",
  "Library & Inf. Science",
  "Mass Communication",
  "Mathematics",
  "Microbiology",
  "Persian",
  "Petroleum Technology",
  "Pharmaceutical Technology",
  "Pharmaceutics",
  "Pharmacognocy",
  "Pharmacology",
  "Pharmacy",
  "Pharmacy Practice",
  "Philosophy",
  "Physics",
  "Physiophy",
  "Political Science",
  "Psychology",
  "Public Administration",
  "Quran wa Sunnah",
  "Research Facility Center",
  "School of Law",
  "Shah Latif Chair",
  "Sindhi",
  "Social Work",
  "Sociology",
  "Special Education",
  "Statistics",
  "Teacher Education",
  "Urdu",
  "Usool Uddin",
  "Visual Studies",
  "Zoology"
];
