const navData = [
  {
    linkText: "Home",
    linkUrl: "/home",
    innerLinkTextAndUrl: [
      { linkText: "About Us", linkUrl: "/" },
      { linkText: "Campus News", linkUrl: "/" },
      { linkText: "Convocation", linkUrl: "/" },
      { linkText: "Downloads", linkUrl: "/" },
      { linkText: "Our Histroy", linkUrl: "/" },
      { linkText: "KURECRUITS", linkUrl: "/" },
    ],
    dropdown: true,
    newCategory: false,
  },
  {
    linkText: "Admissions",
    linkUrl: "/admissions",
    innerLinkTextAndUrl: [
      { linkText: "Admissions Program 2025", linkUrl: "/" },
      { linkText: "M.Phil./Ph.D. & M.S./M.D", linkUrl: "/" },
      { linkText: "Foregin Students' Policy", linkUrl: "/" },
    ],
    dropdown: true,
    newCategory: false,
  },
  {
    linkText: "Faculties",
    linkUrl: "/faculties",
    innerLinkTextAndUrl: [
      { linkText: "Education", linkUrl: "/" },
      { linkText: "Engineering", linkUrl: "/" },
      { linkText: "Islamic Studies", linkUrl: "/" },
      { linkText: "Law", linkUrl: "/" },
      { linkText: "Management Sciences", linkUrl: "/" },
      { linkText: "Medicine", linkUrl: "/" },
      { linkText: "Pharmacy", linkUrl: "/" },
      { linkText: "Science", linkUrl: "/" },
      { linkText: "Arts & Social Sciences", linkUrl: "/" },
      { linkText: "Institutes / Centers", linkUrl: "/" },
    ],
    dropdown: true,
    newCategory: false,
  },
  {
    linkText: "Library",
    linkUrl: "/library",
    innerLinkTextAndUrl: [
      { linkText: "Home", linkUrl: "/" },
      { linkText: "Digital Library", linkUrl: "/" },
      { linkText: "Ebrary", linkUrl: "/" },
    ],
    dropdown: true,
    newCategory: false,
  },
  {
    linkText: "Administration",
    linkUrl: "/administration",
    innerLinkTextAndUrl: [
      { linkText: "Vice Chancellor", linkUrl: "/" },
      { linkText: "Registrar", linkUrl: "/" },
      { linkText: "Syndicate Members", linkUrl: "/" },
      { linkText: "Former Vice Chancellors", linkUrl: "/" },
      { linkText: "Directorates & Offices", linkUrl: "/" },
    ],
    dropdown: true,
    newCategory: false,
  },
  {
    linkText: "Examination",
    linkUrl: "/examination",
    innerLinkTextAndUrl: [
      { linkText: "Annual System", linkUrl: "/" },
      { linkText: "Downladable Forms", linkUrl: "/" },
      { linkText: "Common Questions", linkUrl: "/" },
      { linkText: "Overseas Examination", linkUrl: "/" },
      { linkText: "Semester System", linkUrl: "/" },
      { linkText: "Semeter Role Book", linkUrl: "/" },
      { linkText: "Semeter Fee", linkUrl: "/" },
    ],
    dropdown: true,
    newCategory: false,
  },
  {
    linkText: "Events",
    linkUrl: "/events",
    dropdown: false,
    newCategory: true,
  },
  {
    linkText: "Alumni",
    linkUrl: "/alumni",
    dropdown: false,
    newCategory: false,
  },
  {
    linkText: "Journals",
    linkUrl: "/journals",
    dropdown: false,
    newCategory: false,
  },
];

export default navData;
